### ISSUE TITLE
Can't intersect Bed files

### ISSUE THREAD

**Issue by hputnam** [sr320/student-fish546-2016#3]
I am not able to determine where the DMLs intersect with the bed files. 
See _Determine overlap between the features in the DML and Track files_
https://github.com/hputnam/Oly_Oyster_DNA_Methylation/blob/master/Notebooks/Clustering_Differential_Methylation_R.ipynb

using the ```intersectbed``` command I get the following error
>ERROR: Received illegal bin number 4294967295 from getBin call.
ERROR: Unable to add record to tree.

I think this is the issue, but not sure if there is a fix.
https://groups.google.com/forum/#!topic/bedtools-discuss/t-nQSCxaFGE

Another option may be to format tracks for the methylKit pipeline function ```read.transcript.features```
E.g., 
https://github.com/al2na/methylKit/blob/master/inst/extdata/refseq.hg18.bed.txt

**Comment by sr320** [comment]
Guess 1-
Sort column 1 for each file prior to `intersectbed`

**Comment by hputnam** [comment]
tried sorting both bed files by scaffold id, same error
tried sorting  both bed files by start position, same error

**Comment by sr320** [comment]
Might want to check data - that error seems to be because scaffold > 0.5 million bp - do we have any that big?

**Comment by hputnam** [comment]
Is it that the size is > 0.5 million bp, or the start position?
max start position is 128551

**Comment by sr320** [comment]
How I read that Google Group thread was scaffold size (chromosome)

**Comment by sr320** [comment]
Though pretty sure the longest scaffold is < 150k 
https://github.com/sr320/student-fish546-2016/blob/master/jupyter/00.9-Ostrea-reduction.ipynb

**Comment by hputnam** [comment]
tried double sorting on scaffold and start position as suggested fix for binning issues.... have new error. 
`Error: Sorted input specified, but the file sorted_reorder_Olyv6_blastn-Scaff-30k.gff has the following out of order record scaffold10022 561 145 - . blastn:Ostrea-scaff-30k blastn TR56197|c0_g1_i1`

https://github.com/hputnam/Oly_Oyster_DNA_Methylation/blob/master/Notebooks/Clustering_Differential_Methylation_R.ipynb

**Comment by sr320** [comment]
Guess 2 - start position is larger than stop. (561-145)

could remove this record and test.

**Comment by hputnam** [comment]
This is the case for all the - and the opposite for the +, so this seems like a normal occurrence...

**Comment by hputnam** [comment]
Success!! Last issue was the column formatting in the bed file was lost after reordering. After fixing tabs was able to intersect files.... very few >25% difference in methylation, more if filter is reduced to 10%.

**Comment by sudu59** [comment]
I used to get the same error. I found that once you remove headers this error was resolved.

**Comment by iqraishtiaq** [comment]
how did you solve this issue .... i am working on it but unable to solve it.
kindly help me.
bedtools intersect -a a.bed -b b.bed -wa -wb > output.bed
ERROR: Received illegal bin number 37458 from getBin call.
ERROR: Unable to add record to tree.

**Comment by sr320** [comment]
@iqraishtiaq see https://github.com/sr320/student-fish546-2016/issues/3#issuecomment-258305291
and https://github.com/sr320/student-fish546-2016/issues/3#issuecomment-329272735

likely related to file formats. Feel free to post bed files or partial bed files here for inspection

**Comment by iqraishtiaq** [comment]
`head wheat_col6.bed`

> 1A	199	1683	ENSRNA050013875-T1	0	+
> 1A	5022	6833	ENSRNA050013847-T1	0	+
> 1A	7059	7215	ENSRNA050013913-T1	0	+
> 1A	12316	13827	ENSRNA050013874-T1	0	+
> 1A	15321	16832	ENSRNA050013873-T1	0	+
> 1A	20008	21818	ENSRNA050013836-T1	0	+
> 1A	22044	22200	ENSRNA050013914-T1	0	+
> 1A	28455	30266	ENSRNA050013853-T1	0	+
>1A	30492	30648	ENSRNA050013918-T1	0	+
>1A	37092	38903	ENSRNA050013860-T1	0	+

`head SPRINT_identified_all.res.col3`

> 1A	135397	135398
1A	135420	135421
1A	135429	135430
1A	135446	135447
1A	135450	135451
1A	11664892	11664893
1A	11664901	11664902
1A	11664961	11664962
1A	11665022	11665023
1A	11665066	11665067
